import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Image from "next/image";
import TmdbLogo from "../../public/tmdb-logo.svg";

import Nav from "./components/Nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col">
          <Nav showSearch={true} fixed={true} />
          <main className="flex flex-col">
            {children}
          </main>
          <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
            Credits: This product uses the TMDB API but is not endorsed or certified by TMDB.
            <div className="footer-logo">
              <Image
                className="nav__logo"
                src={TmdbLogo}
                alt=""
              />
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
